In [1]:
import opendatasets as od
import pandas as pd

Go to kaggle.com, to "Your Profile", "Account" and scroll to "API". Select "Create new API token" and use those credentials to log in when requested.

In [ ]:
od.download("https://www.kaggle.com/fedesoriano/company-bankruptcy-prediction/version/2?select=data.csv")
od.download("https://www.kaggle.com/nareshbhat/health-care-data-set-on-heart-attack-possibility?select=heart.csv")

Skipping, found downloaded files in ".\company-bankruptcy-prediction" (use force=True to force download)
Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username:

A folder will be created in the current working directory of your Jupyter Notebook. This folder contains our dataset.

In [3]:
import requests 
import os
import zipfile
import pandas as pd

def download_url(url, save_path, chunk_size=128):
    r = requests.get(url, stream=True)
    with open(save_path, 'wb') as fd:
        for chunk in r.iter_content(chunk_size=chunk_size):
            fd.write(chunk)

download_url('https://www.soa.org/globalassets/assets/files/edu/2020/2020-12-7-exam-pa-data.zip', os.path.join(os.getcwd(), "tmp.zip"))

with zipfile.ZipFile(os.path.join(os.getcwd(), "tmp.zip"), 'r') as zip_ref:
    zip_ref.extractall(os.getcwd())

dataframe = pd.read_csv('December 7 data.csv')

os.remove('December 7 data.csv')
os.remove('tmp.zip')

dataframe

,season,year,hour,holiday,weekday,weathersit,temp,humidity,windspeed,bikes_per_hour
0,1,0,0,0,6,1,0.24,0.81,0.0000,16
1,1,0,1,0,6,1,0.22,0.80,0.0000,40
2,1,0,2,0,6,1,0.22,0.80,0.0000,32
3,1,0,3,0,6,1,0.24,0.75,0.0000,13
4,1,0,4,0,6,1,0.24,0.75,0.0000,1
...,...,...,...,...,...,...,...,...,...,...
17371,1,1,19,0,1,2,0.26,0.60,0.1642,119
17372,1,1,20,0,1,2,0.26,0.60,0.1642,89
17373,1,1,21,0,1,1,0.26,0.60,0.1642,90
17374,1,1,22,0,1,1,0.26,0.56,0.1343,61
17375,1,1,23,0,1,1,0.26,0.65,0.1343,49